version: "3.9"

networks:
  dev:

services:
  test-postgres:
    restart: unless-stopped

    image: "postgres:13.3-alpine"
    container_name: test-postgres
    volumes:
      - test-data:/var/lib/postgresql/data
    ports:
      - 5434:5434
    environment:
      POSTGRES_DB: test

      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGPORT: 5434
    networks:
      - dev
  redis:
    restart: unless-stopped

    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - dev
  test:
    build: ./backend
    command: ["coverage", "run", "-m", "pytest"]
    depends_on:
      - test-postgres
      - redis
volumes:
  test-data:
