version: "3.9"

networks:
  dev:

services:
  #nginx:
  #  image: nginx:stable-alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - './nginx.conf:/etc/nginx/nginx.conf'
  #  depends_on:
  #    - backend
  #    - frontend
  #  networks:
  #    - dev
      
  #frontend:
  #  build:
  #    context: ./frontend
  #  networks:
  #    - dev
  #  ports:
  #    - "3000:3000"
  backend:
    restart: unless-stopped

    build:
      context: ./backend
    networks:
      - dev
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
      - BOT_TOKEN=5166691505:AAEbw80sx5EGT7pB9eT954PTO3WtowUMEME
      - DEVMODE=${DEVMODE}
      - HOST=${HOST}
      - ENGINE=postgresql+asyncpg://zoomayor:zoomayor@zoomayor-postgres:5433/zoomayor
    ports:
      - "4550:4550"
    depends_on:
      - zoomayor-postgres

    volumes:
      - ./backend:/backend  # Монтируем директорию app с хоста в контейнер
      - ./backend/media:/backend/media  # Монтируем директорию app с хоста в контейнер

    working_dir: /backend

  zoomayor-postgres:
    restart: unless-stopped

    image: "postgres:13.3-alpine"
    container_name: zoomayor-postgres
    volumes:
      - zoomayor-data:/var/lib/postgresql/data
    ports:
      - 5433:5433
    environment:
      POSTGRES_DB: zoomayor

      POSTGRES_USER: zoomayor
      POSTGRES_PASSWORD: zoomayor
      PGPORT: 5433
    networks:
      - dev

  redis:
    restart: unless-stopped

    image: "redis:latest"
    ports:
    - "6379:6379"
    networks:
    - dev
volumes:
  zoomayor-data:
