
name: Run tests on any Push event
# Запуск при любом push евенте в ветке deploy
on:
  push:
    branches:
      - 'deploy'
jobs:
  run_tests:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      # Чекаутим код
      - uses: actions/checkout@v3
      # Устанавливаем python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'

      # Кэшируем зависимости
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements
        run: pip install -r backend/requirements.txt
      - name: Run tests
        run: cd backend && coverage run -m pytest && coverage report

  build:
    runs-on: ubuntu-latest
    needs: [run_tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: echo "$PRIVATE_KEY" > id_rsa

      - name: Set file permissions
        run: chmod 600 id_rsa
        
      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
          port: 22
          script: | # set -e остановит выполнение при любой ошибке
            set -e
            cd /home/trumpwifcoin
            git pull https://zahardimidov:${{secrets.REPO_TOKEN}}@github.com/zahardimidov/${{secrets.REPO_NAME}}.git deploy
            docker compose build
            docker compose down
            docker compose --env-file .devenv up -d

